---
title: Deneyin... Catch... -Visual Basic finally deyimi
description: Özel durum işleme Visual Basic Try/Catch/Finally deyimleri ile kullanmayı öğrenin.
ms.date: 12/07/2018
f1_keywords:
- vb.Try...Catch...Finally
- vb.when
- vb.Finally
- vb.Catch
- vb.Try
helpviewer_keywords:
- Try...Catch...Finally statements
- Try statement [Visual Basic]
- try-catch exception handling, Try...Catch...Finally statements
- error handling, while running code
- Try statement [Visual Basic], Try...Catch...Finally
- Finally keyword [Visual Basic], Try...Catch...Finally
- Catch statement [Visual Basic]
- When keyword [Visual Basic]
- Visual Basic code, handling errors while running
- structured exception handling, Try...Catch...Finally statements
ms.assetid: d6488026-ccb3-42b8-a810-0d97b9d6472b
ms.custom: seodec18
ms.openlocfilehash: 2e4fef836b08f536565105dbab76292b2fc4388e
ms.sourcegitcommit: 9b552addadfb57fab0b9e7852ed4f1f1b8a42f8e
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 04/23/2019
ms.locfileid: "61934270"
---
# <a name="trycatchfinally-statement-visual-basic"></a><span data-ttu-id="ddf03-103">Try...Catch...Finally Deyimi (Visual Basic)</span><span class="sxs-lookup"><span data-stu-id="ddf03-103">Try...Catch...Finally Statement (Visual Basic)</span></span>

<span data-ttu-id="ddf03-104">Kod çalışmaya devam ederken, belirli bir kod bloğu içinde oluşabilecek bazı ya da tüm olası hataları işlemek için bir yol sağlar.</span><span class="sxs-lookup"><span data-stu-id="ddf03-104">Provides a way to handle some or all possible errors that may occur in a given block of code, while still running code.</span></span>

## <a name="syntax"></a><span data-ttu-id="ddf03-105">Sözdizimi</span><span class="sxs-lookup"><span data-stu-id="ddf03-105">Syntax</span></span>

```vb
Try
    [ tryStatements ]
    [ Exit Try ]
[ Catch [ exception [ As type ] ] [ When expression ]
    [ catchStatements ]
    [ Exit Try ] ]
[ Catch ... ]
[ Finally
    [ finallyStatements ] ]
End Try
```

## <a name="parts"></a><span data-ttu-id="ddf03-106">Bölümler</span><span class="sxs-lookup"><span data-stu-id="ddf03-106">Parts</span></span>

|<span data-ttu-id="ddf03-107">Terim</span><span class="sxs-lookup"><span data-stu-id="ddf03-107">Term</span></span>|<span data-ttu-id="ddf03-108">Tanım</span><span class="sxs-lookup"><span data-stu-id="ddf03-108">Definition</span></span>|
|---|---|
|`tryStatements`|<span data-ttu-id="ddf03-109">İsteğe bağlı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-109">Optional.</span></span> <span data-ttu-id="ddf03-110">Deyim, burada bir hata oluşabilir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-110">Statement(s) where an error can occur.</span></span> <span data-ttu-id="ddf03-111">Bileşik deyim olabilir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-111">Can be a compound statement.</span></span>|
|`Catch`|<span data-ttu-id="ddf03-112">İsteğe bağlı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-112">Optional.</span></span> <span data-ttu-id="ddf03-113">Birden çok `Catch` izin engeller.</span><span class="sxs-lookup"><span data-stu-id="ddf03-113">Multiple `Catch` blocks permitted.</span></span> <span data-ttu-id="ddf03-114">Bir özel durum işleme sırasında oluşursa `Try` engelleme, her `Catch` deyimi, özel durum ile işleme olup olmadığını belirlemek için metinsel sırayla incelenir `exception` temsil eden özel durum oluşturuldu.</span><span class="sxs-lookup"><span data-stu-id="ddf03-114">If an exception occurs when processing the `Try` block, each `Catch` statement is examined in textual order to determine whether it handles the exception, with `exception` representing the exception that has been thrown.</span></span>|
|`exception`|<span data-ttu-id="ddf03-115">İsteğe bağlı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-115">Optional.</span></span> <span data-ttu-id="ddf03-116">Herhangi bir değişken adı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-116">Any variable name.</span></span> <span data-ttu-id="ddf03-117">Başlangıç değeri oluşan `exception` hatadır değeridir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-117">The initial value of `exception` is the value of the thrown error.</span></span> <span data-ttu-id="ddf03-118">İle kullanılan `Catch` hatanın belirtileceği yakalandı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-118">Used with `Catch` to specify the error caught.</span></span> <span data-ttu-id="ddf03-119">Atlanırsa, `Catch` deyimi herhangi bir özel durumu yakalar.</span><span class="sxs-lookup"><span data-stu-id="ddf03-119">If omitted, the `Catch` statement catches any exception.</span></span>|
|`type`|<span data-ttu-id="ddf03-120">İsteğe bağlı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-120">Optional.</span></span> <span data-ttu-id="ddf03-121">Sınıf filtre türünü belirtir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-121">Specifies the type of class filter.</span></span> <span data-ttu-id="ddf03-122">Varsa değerini `exception` tarafından belirtilen türde `type` veya türetilmiş bir tür tanımlayıcısı özel durum nesnesine bağlı olur.</span><span class="sxs-lookup"><span data-stu-id="ddf03-122">If the value of `exception` is of the type specified by `type` or of a derived type, the identifier becomes bound to the exception object.</span></span>|
|`When`|<span data-ttu-id="ddf03-123">İsteğe bağlı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-123">Optional.</span></span> <span data-ttu-id="ddf03-124">A `Catch` deyimiyle bir `When` yan tümcesi, özel durumları yakalar yalnızca `expression` değerlendiren `True`.</span><span class="sxs-lookup"><span data-stu-id="ddf03-124">A `Catch` statement with a `When` clause catches exceptions only when `expression` evaluates to `True`.</span></span> <span data-ttu-id="ddf03-125">A `When` yan tümcesi yalnızca özel durumun türünü denetledikten sonra uygulanır ve `expression` özel durumu temsil eden tanımlayıcı başvurabilir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-125">A `When` clause is applied only after checking the type of the exception, and `expression` may refer to the identifier representing the exception.</span></span>|
|`expression`|<span data-ttu-id="ddf03-126">İsteğe bağlı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-126">Optional.</span></span> <span data-ttu-id="ddf03-127">Örtük olarak dönüştürülebilir olmalıdır `Boolean`.</span><span class="sxs-lookup"><span data-stu-id="ddf03-127">Must be implicitly convertible to `Boolean`.</span></span> <span data-ttu-id="ddf03-128">Genel filtre açıklar herhangi bir ifade.</span><span class="sxs-lookup"><span data-stu-id="ddf03-128">Any expression that describes a generic filter.</span></span> <span data-ttu-id="ddf03-129">Genellikle, hata numarasına göre filtrelemek için kullanılır.</span><span class="sxs-lookup"><span data-stu-id="ddf03-129">Typically used to filter by error number.</span></span> <span data-ttu-id="ddf03-130">İle kullanılan `When` koşullar altında hata yakalandı belirtmek için anahtar sözcüğü.</span><span class="sxs-lookup"><span data-stu-id="ddf03-130">Used with `When` keyword to specify circumstances under which the error is caught.</span></span>|
|`catchStatements`|<span data-ttu-id="ddf03-131">İsteğe bağlı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-131">Optional.</span></span> <span data-ttu-id="ddf03-132">İlişkili içinde oluşan hataları işlemek için deyim `Try` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-132">Statement(s) to handle errors that occur in the associated `Try` block.</span></span> <span data-ttu-id="ddf03-133">Bileşik deyim olabilir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-133">Can be a compound statement.</span></span>|
|`Exit Try`|<span data-ttu-id="ddf03-134">İsteğe bağlı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-134">Optional.</span></span> <span data-ttu-id="ddf03-135">/ Keser anahtar sözcüğü `Try...Catch...Finally` yapısı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-135">Keyword that breaks out of the `Try...Catch...Finally` structure.</span></span> <span data-ttu-id="ddf03-136">Yürütmeyi hemen kod ile devam ettirir `End Try` deyimi.</span><span class="sxs-lookup"><span data-stu-id="ddf03-136">Execution resumes with the code immediately following the `End Try` statement.</span></span> <span data-ttu-id="ddf03-137">`Finally` Deyimi hala yürütülür.</span><span class="sxs-lookup"><span data-stu-id="ddf03-137">The `Finally` statement will still be executed.</span></span> <span data-ttu-id="ddf03-138">İçinde izin verilmiyor `Finally` engeller.</span><span class="sxs-lookup"><span data-stu-id="ddf03-138">Not allowed in `Finally` blocks.</span></span>|
|`Finally`|<span data-ttu-id="ddf03-139">İsteğe bağlı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-139">Optional.</span></span> <span data-ttu-id="ddf03-140">A `Finally` blok herhangi bir bölümü yürütme ayrıldığında her zaman yürütülür `Try...Catch` deyimi.</span><span class="sxs-lookup"><span data-stu-id="ddf03-140">A `Finally` block is always executed when execution leaves any part of the `Try...Catch` statement.</span></span>|
|`finallyStatements`|<span data-ttu-id="ddf03-141">İsteğe bağlı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-141">Optional.</span></span> <span data-ttu-id="ddf03-142">Diğer tüm hata işleme gerçekleştikten sonra yürütülen deyim.</span><span class="sxs-lookup"><span data-stu-id="ddf03-142">Statement(s) that are executed after all other error processing has occurred.</span></span>|
|`End Try`|<span data-ttu-id="ddf03-143">Sonlandırır `Try...Catch...Finally` yapısı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-143">Terminates the `Try...Catch...Finally` structure.</span></span>|

## <a name="remarks"></a><span data-ttu-id="ddf03-144">Açıklamalar</span><span class="sxs-lookup"><span data-stu-id="ddf03-144">Remarks</span></span>

<span data-ttu-id="ddf03-145">Belirli bir özel durum kodu belirli bir bölümünü sırasında oluşabilecek bekliyorsanız, kod yerleştirecek bir `Try` engelleme ve kullanmak bir `Catch` denetimini sürdürme ve bu durum oluşursa özel durum işleme bloğu.</span><span class="sxs-lookup"><span data-stu-id="ddf03-145">If you expect that a particular exception might occur during a particular section of code, put the code in a `Try` block and use a `Catch` block to retain control and handle the exception if it occurs.</span></span>

<span data-ttu-id="ddf03-146">A `Try…Catch` deyimi oluşur bir `Try` blok izlenen bir veya daha fazla tarafından `Catch` çeşitli özel durumlar için işleyiciler belirten yan tümceleri.</span><span class="sxs-lookup"><span data-stu-id="ddf03-146">A `Try…Catch` statement consists of a `Try` block followed by one or more `Catch` clauses, which specify handlers for various exceptions.</span></span> <span data-ttu-id="ddf03-147">Bir özel durum harekete geçirildiğinde bir `Try` engelleme, Visual Basic arar `Catch` özel durumu işleyen bir ifade.</span><span class="sxs-lookup"><span data-stu-id="ddf03-147">When an exception is thrown in a `Try` block, Visual Basic looks for the `Catch` statement that handles the exception.</span></span> <span data-ttu-id="ddf03-148">Eşleşen bir `Catch` deyimi bulunamadı, Visual Basic, çağrı yığını ayarlama ve benzeri geçerli bir yöntemi çağıran yönteme inceler.</span><span class="sxs-lookup"><span data-stu-id="ddf03-148">If a matching `Catch` statement is not found, Visual Basic examines the method that called the current method, and so on up the call stack.</span></span> <span data-ttu-id="ddf03-149">Hayır ise `Catch` bloğu bulundu, Visual Basic, kullanıcıya bir işlenmeyen özel durum iletisi görüntüler ve programın yürütülmesini durdurur.</span><span class="sxs-lookup"><span data-stu-id="ddf03-149">If no `Catch` block is found, Visual Basic displays an unhandled exception message to the user and stops execution of the program.</span></span>

<span data-ttu-id="ddf03-150">Birden fazla kullanabileceğiniz `Catch` deyiminde bir `Try…Catch` deyimi.</span><span class="sxs-lookup"><span data-stu-id="ddf03-150">You can use more than one `Catch` statement in a `Try…Catch` statement.</span></span> <span data-ttu-id="ddf03-151">Bu sırasını `Catch` yan tümceleri, bunlar sırayla incelenir olduğundan önemlidir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-151">If you do this, the order of the `Catch` clauses is significant because they are examined in order.</span></span> <span data-ttu-id="ddf03-152">Less yazımına özgü olanlardan önce daha özel istisnaları yakalayın.</span><span class="sxs-lookup"><span data-stu-id="ddf03-152">Catch the more specific exceptions before the less specific ones.</span></span>

<span data-ttu-id="ddf03-153">Aşağıdaki `Catch` deyimi koşulları en az özel olan ve tüm türetilen özel durum <xref:System.Exception> sınıfı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-153">The following `Catch` statement conditions are the least specific, and will catch all exceptions that derive from the <xref:System.Exception> class.</span></span> <span data-ttu-id="ddf03-154">Bu farklılıkların biri son normalde kullanması gereken `Catch` engelleyin `Try...Catch...Finally` beklediğiniz tüm belirli özel durumları yakalama sonra yapısı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-154">You should ordinarily use one of these variations as the last `Catch` block in the `Try...Catch...Finally` structure, after catching all the specific exceptions you expect.</span></span> <span data-ttu-id="ddf03-155">Denetim akışı ulaşabilirsiniz hiçbir zaman bir `Catch` ya da bu farklılıkların izleyen blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-155">Control flow can never reach a `Catch` block that follows either of these variations.</span></span>

- <span data-ttu-id="ddf03-156">`type` Olduğu `Exception`, örneğin: `Catch ex As Exception`</span><span class="sxs-lookup"><span data-stu-id="ddf03-156">The `type` is `Exception`, for example: `Catch ex As Exception`</span></span>

- <span data-ttu-id="ddf03-157">Deyim olmayan `exception` değişken, örneğin: `Catch`</span><span class="sxs-lookup"><span data-stu-id="ddf03-157">The statement has no `exception` variable, for example: `Catch`</span></span>

<span data-ttu-id="ddf03-158">Olduğunda bir `Try…Catch…Finally` deyimi iç içe başka `Try` blok, Visual Basic ilk inceler her `Catch` en içteki deyiminde `Try` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-158">When a `Try…Catch…Finally` statement is nested in another `Try` block, Visual Basic first examines each `Catch` statement in the innermost `Try` block.</span></span> <span data-ttu-id="ddf03-159">Hiç eşleşen `Catch` deyimi bulundu, aramaya devam eder `Catch` bilgilerinin dış `Try…Catch…Finally` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-159">If no matching `Catch` statement is found, the search proceeds to the `Catch` statements of the outer `Try…Catch…Finally` block.</span></span>

<span data-ttu-id="ddf03-160">Yerel değişkenleri bir `Try` blok içinde kullanılabilir olmayan bir `Catch` çünkü bunlar ayrı bloklarda engelleyin.</span><span class="sxs-lookup"><span data-stu-id="ddf03-160">Local variables from a `Try` block are not available in a `Catch` block because they are separate blocks.</span></span> <span data-ttu-id="ddf03-161">Birden fazla blok içinde bir değişken kullanmak istiyorsanız, dışında değişkenini tanımlamak `Try...Catch...Finally` yapısı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-161">If you want to use a variable in more than one block, declare the variable outside the `Try...Catch...Finally` structure.</span></span>

> [!TIP]
> <span data-ttu-id="ddf03-162">`Try…Catch…Finally` Deyimi bir IntelliSense kod parçacığı kullanılabilir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-162">The `Try…Catch…Finally` statement is available as an IntelliSense code snippet.</span></span> <span data-ttu-id="ddf03-163">Kod parçacıkları Yöneticisi'nde **kod desenleri - IF, adet için Try Catch, özellik vb.**, ardından **hata işleme (özel)**.</span><span class="sxs-lookup"><span data-stu-id="ddf03-163">In the Code Snippets Manager, expand **Code Patterns - If, For Each, Try Catch, Property, etc**, and then **Error Handling (Exceptions)**.</span></span> <span data-ttu-id="ddf03-164">Daha fazla bilgi için [kod parçacıkları](/visualstudio/ide/code-snippets).</span><span class="sxs-lookup"><span data-stu-id="ddf03-164">For more information, see [Code Snippets](/visualstudio/ide/code-snippets).</span></span>

## <a name="finally-block"></a><span data-ttu-id="ddf03-165">Finally bloğu</span><span class="sxs-lookup"><span data-stu-id="ddf03-165">Finally block</span></span>

<span data-ttu-id="ddf03-166">Çıkış önce çalıştırılması gereken bir veya daha fazla deyimleri varsa `Try` yapısı, kullanan bir `Finally` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-166">If you have one or more statements that must run before you exit the `Try` structure, use a `Finally` block.</span></span> <span data-ttu-id="ddf03-167">Denetim geçtiği `Finally` yalnızca tanesi geçirmeden önce block `Try…Catch` yapısı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-167">Control passes to the `Finally` block just before it passes out of the `Try…Catch` structure.</span></span> <span data-ttu-id="ddf03-168">İçinde herhangi bir özel bir durum oluştuğunda olsa bile bu geçerlidir `Try` yapısı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-168">This is true even if an exception occurs anywhere inside the `Try` structure.</span></span>

<span data-ttu-id="ddf03-169">A `Finally` blok, bir özel durum olsa bile, herhangi bir kod çalıştıran yürütülmesi gereken için yararlıdır.</span><span class="sxs-lookup"><span data-stu-id="ddf03-169">A `Finally` block is useful for running any code that must execute even if there is an exception.</span></span> <span data-ttu-id="ddf03-170">Denetim geçirildiğinde `Finally` bakılmaksızın nasıl blok `Try...Catch` block çıkar.</span><span class="sxs-lookup"><span data-stu-id="ddf03-170">Control is passed to the `Finally` block regardless of how the `Try...Catch` block exits.</span></span>

<span data-ttu-id="ddf03-171">Kodda bir `Finally` kodunuzu karşılaştığında bile bloğu çalışır bir `Return` deyiminde bir `Try` veya `Catch` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-171">The code in a `Finally` block runs even if your code encounters a `Return` statement in a `Try` or `Catch` block.</span></span> <span data-ttu-id="ddf03-172">Denetim gelen geçirmek değil bir `Try` veya `Catch` block karşılık gelen `Finally` aşağıdaki durumlarda engelle:</span><span class="sxs-lookup"><span data-stu-id="ddf03-172">Control does not pass from a `Try` or `Catch` block to the corresponding `Finally` block in the following cases:</span></span>

- <span data-ttu-id="ddf03-173">Bir [End deyimi](end-statement.md) ile karşılaşılırsa `Try` veya `Catch` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-173">An [End Statement](end-statement.md) is encountered in the `Try` or `Catch` block.</span></span>

- <span data-ttu-id="ddf03-174">A <xref:System.StackOverflowException> oluşturulur `Try` veya `Catch` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-174">A <xref:System.StackOverflowException> is thrown in the `Try` or `Catch` block.</span></span>

<span data-ttu-id="ddf03-175">Açıkça yürütme içine aktarmak için geçerli değil bir `Finally` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-175">It is not valid to explicitly transfer execution into a `Finally` block.</span></span> <span data-ttu-id="ddf03-176">Yürütme / aktarma bir `Finally` bloğu geçerli olmayan bir özel durum, dışında.</span><span class="sxs-lookup"><span data-stu-id="ddf03-176">Transferring execution out of a `Finally` block is not valid, except through an exception.</span></span>

<span data-ttu-id="ddf03-177">Varsa bir `Try` deyimi en az bir içermiyor `Catch` bloğu içermesi gereken bir `Finally` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-177">If a `Try` statement does not contain at least one `Catch` block, it must contain a `Finally` block.</span></span>

> [!TIP]
> <span data-ttu-id="ddf03-178">Belirli özel durumları yakalamak yoksa `Using` deyimi davranacağını gibi bir `Try…Finally` blok ve nasıl blok çıkış bağımsız olarak bağlı olarak, kaynakların elden garanti eder.</span><span class="sxs-lookup"><span data-stu-id="ddf03-178">If you do not have to catch specific exceptions, the `Using` statement behaves like a `Try…Finally` block, and guarantees disposal of the resources, regardless of how you exit the block.</span></span> <span data-ttu-id="ddf03-179">İşlenmeyen bir özel durumla bile bu geçerlidir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-179">This is true even with an unhandled exception.</span></span> <span data-ttu-id="ddf03-180">Daha fazla bilgi için [Using deyimi](using-statement.md).</span><span class="sxs-lookup"><span data-stu-id="ddf03-180">For more information, see [Using Statement](using-statement.md).</span></span>

## <a name="exception-argument"></a><span data-ttu-id="ddf03-181">Özel durum bağımsız değişken</span><span class="sxs-lookup"><span data-stu-id="ddf03-181">Exception argument</span></span>

<span data-ttu-id="ddf03-182">`Catch` Blok `exception` bağımsız değişken öğesinin bir örneğiyse <xref:System.Exception> sınıfı veya türetildiği bir sınıf `Exception` sınıfı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-182">The `Catch` block `exception` argument is an instance of the <xref:System.Exception> class or a class that derives from the `Exception` class.</span></span> <span data-ttu-id="ddf03-183">`Exception` Karşılık gelen sınıf örneği oluştu hata `Try` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-183">The `Exception` class instance corresponds to the error that occurred in the `Try` block.</span></span>

<span data-ttu-id="ddf03-184">Özelliklerini `Exception` nesnesi bir özel durum konumunu ve sorunun kaynağını belirlemek için Yardım.</span><span class="sxs-lookup"><span data-stu-id="ddf03-184">The properties of the `Exception` object help to identify the cause and location of an exception.</span></span> <span data-ttu-id="ddf03-185">Örneğin, <xref:System.Exception.StackTrace%2A> özelliği, kod hatasının oluştuğu bulmanıza yardımcı olacak özel durumu götüren çağırılan yöntemleri listeler.</span><span class="sxs-lookup"><span data-stu-id="ddf03-185">For example, the <xref:System.Exception.StackTrace%2A> property lists the called methods that led to the exception, helping you find where the error occurred in the code.</span></span> <span data-ttu-id="ddf03-186"><xref:System.Exception.Message%2A> özel durumu açıklayan bir ileti döndürür.</span><span class="sxs-lookup"><span data-stu-id="ddf03-186"><xref:System.Exception.Message%2A> returns a message that describes the exception.</span></span> <span data-ttu-id="ddf03-187"><xref:System.Exception.HelpLink%2A> bir bağlantı, ilişkili bir Yardım dosyasına döndürür.</span><span class="sxs-lookup"><span data-stu-id="ddf03-187"><xref:System.Exception.HelpLink%2A> returns a link to an associated Help file.</span></span> <span data-ttu-id="ddf03-188"><xref:System.Exception.InnerException%2A> döndürür `Exception` veya geçerli özel duruma neden olan bir nesne döndürür `Nothing` hiçbir özgün ise `Exception`.</span><span class="sxs-lookup"><span data-stu-id="ddf03-188"><xref:System.Exception.InnerException%2A> returns the `Exception` object that caused the current exception, or it returns `Nothing` if there is no original `Exception`.</span></span>

## <a name="considerations-when-using-a-trycatch-statement"></a><span data-ttu-id="ddf03-189">Bir Try kullanmayla ilgili konular... Catch deyimi</span><span class="sxs-lookup"><span data-stu-id="ddf03-189">Considerations when using a Try…Catch statement</span></span>

<span data-ttu-id="ddf03-190">Kullanım bir `Try…Catch` deyimi yalnızca olağan dışı ya da beklenmeyen programı olayların sinyal.</span><span class="sxs-lookup"><span data-stu-id="ddf03-190">Use a `Try…Catch` statement only to signal the occurrence of unusual or unanticipated program events.</span></span> <span data-ttu-id="ddf03-191">Bunun nedeni aşağıdakileri içerir:</span><span class="sxs-lookup"><span data-stu-id="ddf03-191">Reasons for this include the following:</span></span>

- <span data-ttu-id="ddf03-192">Çalışma zamanında özel durumları yakalama ek yükü oluşturur ve özel durumlar önlemek için önceden denetlemekten daha yavaş olması olasıdır.</span><span class="sxs-lookup"><span data-stu-id="ddf03-192">Catching exceptions at runtime creates additional overhead, and is likely to be slower than pre-checking to avoid exceptions.</span></span>

- <span data-ttu-id="ddf03-193">Varsa bir `Catch` blok düzgün işlenmez, özel durum kullanıcılara doğru bildirilmeyebilir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-193">If a `Catch` block is not handled correctly, the exception might not be reported correctly to users.</span></span>

- <span data-ttu-id="ddf03-194">Özel durum işleme bir program daha karmaşık hale getirir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-194">Exception handling makes a program more complex.</span></span>

<span data-ttu-id="ddf03-195">Her zaman gereksinim duymadığınız bir `Try…Catch` deyimi, arıza oluştuğu sırada bir koşul için denetlenecek.</span><span class="sxs-lookup"><span data-stu-id="ddf03-195">You do not always need a `Try…Catch` statement to check for a condition that is likely to occur.</span></span> <span data-ttu-id="ddf03-196">Aşağıdaki örnek, bir dosyayı açmak denemeden önce mevcut olup olmadığını denetler.</span><span class="sxs-lookup"><span data-stu-id="ddf03-196">The following example checks whether a file exists before trying to open it.</span></span> <span data-ttu-id="ddf03-197">Bu tarafından oluşturulan bir özel durum yakalama gereksinimini azaltır <xref:System.IO.File.OpenText%2A> yöntemi.</span><span class="sxs-lookup"><span data-stu-id="ddf03-197">This reduces the need for catching an exception thrown by the <xref:System.IO.File.OpenText%2A> method.</span></span>

[!code-vb[VbVbalrStatements#94](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrStatements/VB/Class1.vb#94)]

<span data-ttu-id="ddf03-198">Bu kodu olun `Catch` blokları düzgün bir şekilde rapor edebilir, kullanıcılara özel durumları iş parçacığı günlük kaydı veya uygun iletileri üzerinden.</span><span class="sxs-lookup"><span data-stu-id="ddf03-198">Ensure that code in `Catch` blocks can properly report exceptions to users, whether through thread-safe logging or appropriate messages.</span></span> <span data-ttu-id="ddf03-199">Aksi takdirde, özel durumlar bilinmeyen kalabilir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-199">Otherwise, exceptions might remain unknown.</span></span>

## <a name="async-methods"></a><span data-ttu-id="ddf03-200">Zaman uyumsuz yöntemler</span><span class="sxs-lookup"><span data-stu-id="ddf03-200">Async methods</span></span>

<span data-ttu-id="ddf03-201">Bir yöntem ile işaretlerseniz [zaman uyumsuz](../modifiers/async.md) kullanabileceğiniz değiştiricisi [Await](../operators/await-operator.md) yönteminde işleci.</span><span class="sxs-lookup"><span data-stu-id="ddf03-201">If you mark a method with the [Async](../modifiers/async.md) modifier, you can use the [Await](../operators/await-operator.md) operator in the method.</span></span> <span data-ttu-id="ddf03-202">With deyimi `Await` işleci awaited görevi tamamlanıncaya kadar yöntemin yürütülmesini askıya alır.</span><span class="sxs-lookup"><span data-stu-id="ddf03-202">A statement with the `Await` operator suspends execution of the method until the awaited task completes.</span></span> <span data-ttu-id="ddf03-203">Görev, devam eden çalışmayı temsil eder.</span><span class="sxs-lookup"><span data-stu-id="ddf03-203">The task represents ongoing work.</span></span> <span data-ttu-id="ddf03-204">Zaman ile ilişkili görev `Await` işleci tamamlandıktan, aynı yöntemin yürütülmesine devam ettirir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-204">When the task that's associated with the `Await` operator finishes, execution resumes in the same method.</span></span> <span data-ttu-id="ddf03-205">Daha fazla bilgi için [zaman uyumsuz programlarda akış kontrolü](../../../visual-basic/programming-guide/concepts/async/control-flow-in-async-programs.md).</span><span class="sxs-lookup"><span data-stu-id="ddf03-205">For more information, see [Control Flow in Async Programs](../../../visual-basic/programming-guide/concepts/async/control-flow-in-async-programs.md).</span></span>

<span data-ttu-id="ddf03-206">Zaman uyumsuz bir yöntem tarafından döndürülen görev hatalı bir durumda, işlenmeyen bir özel durum nedeniyle tamamlandı belirten sonlandırabiliriz.</span><span class="sxs-lookup"><span data-stu-id="ddf03-206">A task returned by an Async method may end in a faulted state, indicating that it completed due to an unhandled exception.</span></span> <span data-ttu-id="ddf03-207">Bir görev sonuçlanır bir iptal edilmiş duruma da bitemez bir `OperationCanceledException` await ifadesi dışında oluşturulan.</span><span class="sxs-lookup"><span data-stu-id="ddf03-207">A task may also end in a canceled state, which results in an `OperationCanceledException` being thrown out of the await expression.</span></span> <span data-ttu-id="ddf03-208">Herhangi bir türde özel durum yakalamak için yerleştirin `Await` görev ile ilişkili ifade bir `Try` blok ve özel durumu `Catch` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-208">To catch either type of exception, place the `Await` expression that's associated with the task in a `Try` block, and catch the exception in the `Catch` block.</span></span> <span data-ttu-id="ddf03-209">Örnek bu konunun ilerleyen bölümlerinde verilmiştir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-209">An example is provided later in this topic.</span></span>

<span data-ttu-id="ddf03-210">Bir görev birden çok özel durum, hatalı için sorumlu hatalı bir durumda olabilir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-210">A task can be in a faulted state because multiple exceptions were responsible for its faulting.</span></span> <span data-ttu-id="ddf03-211">Örneğin, görev yapılan bir çağrının sonucu olabilir <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=nameWithType>.</span><span class="sxs-lookup"><span data-stu-id="ddf03-211">For example, the task might be the result of a call to <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=nameWithType>.</span></span> <span data-ttu-id="ddf03-212">Böyle bir görevi beklerken, özel durum yakalandı yalnızca bir özel durumlar ve özel durum yakalandı tahmin edemezsiniz.</span><span class="sxs-lookup"><span data-stu-id="ddf03-212">When you await such a task, the caught exception is only one of the exceptions, and you can't predict which exception will be caught.</span></span> <span data-ttu-id="ddf03-213">Örnek bu konunun ilerleyen bölümlerinde verilmiştir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-213">An example is provided later in this topic.</span></span>

<span data-ttu-id="ddf03-214">Bir `Await` ifade olamaz içinde bir `Catch` blok veya `Finally` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-214">An `Await` expression can't be inside a `Catch` block or `Finally` block.</span></span>

## <a name="iterators"></a><span data-ttu-id="ddf03-215">Yineleyiciler</span><span class="sxs-lookup"><span data-stu-id="ddf03-215">Iterators</span></span>

<span data-ttu-id="ddf03-216">Yineleyici işleve veya `Get` erişimci bir koleksiyon üzerinde özel yineleme gerçekleştirir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-216">An iterator function or `Get` accessor performs a custom iteration over a collection.</span></span> <span data-ttu-id="ddf03-217">Yineleyici bir [Yield](yield-statement.md) deyimini her öğesini birer birer koleksiyonunun bir döndürür.</span><span class="sxs-lookup"><span data-stu-id="ddf03-217">An iterator uses a [Yield](yield-statement.md) statement to return each element of the collection one at a time.</span></span> <span data-ttu-id="ddf03-218">Kullanarak bir yineleyici işlevi çağırmak bir [her biri için... Sonraki deyimi](for-each-next-statement.md).</span><span class="sxs-lookup"><span data-stu-id="ddf03-218">You call an iterator function by using a [For Each...Next Statement](for-each-next-statement.md).</span></span>

<span data-ttu-id="ddf03-219">A `Yield` deyimi içinde olabilir bir `Try` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-219">A `Yield` statement can be inside a `Try` block.</span></span> <span data-ttu-id="ddf03-220">A `Try` içeren blok bir `Yield` deyimi olabilir `Catch` engeller ve olabilir bir `Finally` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-220">A `Try` block that contains a `Yield` statement can have `Catch` blocks, and can have a `Finally` block.</span></span> <span data-ttu-id="ddf03-221">"Deneyin blokları Visual Basic" bölümüne bakın [yineleyiciler](../../programming-guide/concepts/iterators.md) örneği.</span><span class="sxs-lookup"><span data-stu-id="ddf03-221">See the "Try Blocks in Visual Basic" section of [Iterators](../../programming-guide/concepts/iterators.md) for an example.</span></span>

<span data-ttu-id="ddf03-222">A `Yield` deyimi içinde olamaz bir `Catch` blok veya `Finally` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-222">A `Yield` statement cannot be inside a `Catch` block or a `Finally` block.</span></span>

<span data-ttu-id="ddf03-223">Varsa `For Each` gövdesi (yineleyici işleve dışında) bir özel durum oluşturursa bir `Catch` yineleyici işleve bloğunda yürütülmedi, ancak bir `Finally` yineleyici işleve bloğunda yürütülür.</span><span class="sxs-lookup"><span data-stu-id="ddf03-223">If the `For Each` body (outside of the iterator function) throws an exception, a `Catch` block in the iterator function is not executed, but a `Finally` block in the iterator function is executed.</span></span> <span data-ttu-id="ddf03-224">A `Catch` blok içinde bir yineleyici işlevi yineleyici işlevde oluşan özel durumları yakalar.</span><span class="sxs-lookup"><span data-stu-id="ddf03-224">A `Catch` block inside an iterator function catches only exceptions that occur inside the iterator function.</span></span>

## <a name="partial-trust-situations"></a><span data-ttu-id="ddf03-225">Kısmi güven durumları</span><span class="sxs-lookup"><span data-stu-id="ddf03-225">Partial-trust situations</span></span>

<span data-ttu-id="ddf03-226">Bir ağ paylaşımında barındırılan bir uygulamanın gibi kısmi güven durumlarında `Try...Catch...Finally` çağrı içeren yöntemi çağrılmadan önce gerçekleşen bir güvenlik özel durumları yakalamaz.</span><span class="sxs-lookup"><span data-stu-id="ddf03-226">In partial-trust situations, such as an application hosted on a network share, `Try...Catch...Finally` does not catch security exceptions that occur before the method that contains the call is invoked.</span></span> <span data-ttu-id="ddf03-227">Sunucu paylaşımı üzerindeki put ve oradan çalıştırın, aşağıdaki örnekte, bir hata oluşturur. "System.Security.SecurityException: İstek başarısız oldu."</span><span class="sxs-lookup"><span data-stu-id="ddf03-227">The following example, when you put it on a server share and run from there, produces the error "System.Security.SecurityException: Request Failed."</span></span> <span data-ttu-id="ddf03-228">Güvenlik özel durumları hakkında daha fazla bilgi için bkz. <xref:System.Security.SecurityException> sınıfı.</span><span class="sxs-lookup"><span data-stu-id="ddf03-228">For more information about security exceptions, see the <xref:System.Security.SecurityException> class.</span></span>

[!code-vb[VbVbalrStatements#85](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrStatements/VB/Class1.vb#85)]

<span data-ttu-id="ddf03-229">Böyle bir kısmi güven durumda moduna sahip `Process.Start` ayrı bir deyimde `Sub`.</span><span class="sxs-lookup"><span data-stu-id="ddf03-229">In such a partial-trust situation, you have to put the `Process.Start` statement in a separate `Sub`.</span></span> <span data-ttu-id="ddf03-230">İlk çağrı `Sub` başarısız olur.</span><span class="sxs-lookup"><span data-stu-id="ddf03-230">The initial call to the `Sub` will fail.</span></span> <span data-ttu-id="ddf03-231">Böylece `Try...Catch` önce bunu yakalayıp yakalamayacağınıza karar `Sub` içeren `Process.Start` başlatılır ve güvenlik özel durumu üretti.</span><span class="sxs-lookup"><span data-stu-id="ddf03-231">This enables `Try...Catch` to catch it before the `Sub` that contains `Process.Start` is started and the security exception produced.</span></span>

## <a name="examples"></a><span data-ttu-id="ddf03-232">Örnekler</span><span class="sxs-lookup"><span data-stu-id="ddf03-232">Examples</span></span>

### <a name="the-structure-of-trycatchfinally"></a><span data-ttu-id="ddf03-233">Try yapısı... Catch... Son olarak</span><span class="sxs-lookup"><span data-stu-id="ddf03-233">The structure of Try...Catch...Finally</span></span>

<span data-ttu-id="ddf03-234">Yapısı aşağıdaki örnekte `Try...Catch...Finally` deyimi.</span><span class="sxs-lookup"><span data-stu-id="ddf03-234">The following example illustrates the structure of the `Try...Catch...Finally` statement.</span></span>

[!code-vb[VbVbalrStatements#86](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrStatements/VB/Class1.vb#86)]  

### <a name="exception-in-a-method-called-from-a-try-block"></a><span data-ttu-id="ddf03-235">Bir Try bloğundan adlı bir yöntemde özel durum</span><span class="sxs-lookup"><span data-stu-id="ddf03-235">Exception in a method called from a Try block</span></span>

<span data-ttu-id="ddf03-236">Aşağıdaki örnekte, `CreateException` yöntem bir `NullReferenceException`.</span><span class="sxs-lookup"><span data-stu-id="ddf03-236">In the following example, the `CreateException` method throws a `NullReferenceException`.</span></span> <span data-ttu-id="ddf03-237">Özel durum oluşturan kodu kullanımda olmayan bir `Try` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-237">The code that generates the exception is not in a `Try` block.</span></span> <span data-ttu-id="ddf03-238">Bu nedenle, `CreateException` yöntemi özel durum işlemez.</span><span class="sxs-lookup"><span data-stu-id="ddf03-238">Therefore, the `CreateException` method does not handle the exception.</span></span> <span data-ttu-id="ddf03-239">`RunSample` Olduğundan, yöntemi özel durum işleme çağrısı `CreateException` yöntemdir içinde bir `Try` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-239">The `RunSample` method does handle the exception because the call to the `CreateException` method is in a `Try` block.</span></span>

<span data-ttu-id="ddf03-240">Örnek içerir `Catch` deyimleri için birden fazla özel durumlar, sipariş gelen en belirli en genel.</span><span class="sxs-lookup"><span data-stu-id="ddf03-240">The example includes `Catch` statements for several types of exceptions, ordered from the most specific to the most general.</span></span>

[!code-vb[VbVbalrStatements#91](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrStatements/VB/Class1.vb#91)]

### <a name="the-catch-when-statement"></a><span data-ttu-id="ddf03-241">Catch deyimi</span><span class="sxs-lookup"><span data-stu-id="ddf03-241">The Catch When statement</span></span>

<span data-ttu-id="ddf03-242">Aşağıdaki örnek nasıl kullanılacağını gösteren bir `Catch When` üzerinde bir koşullu ifade filtrelemek için deyimi.</span><span class="sxs-lookup"><span data-stu-id="ddf03-242">The following example shows how to use a `Catch When` statement to filter on a conditional expression.</span></span> <span data-ttu-id="ddf03-243">Koşullu ifade değerlendirilirse `True`, kodda `Catch` bloğu çalışır.</span><span class="sxs-lookup"><span data-stu-id="ddf03-243">If the conditional expression evaluates to `True`, the code in the `Catch` block runs.</span></span>

[!code-vb[VbVbalrStatements#92](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrStatements/VB/Class1.vb#92)]

### <a name="nested-try-statements"></a><span data-ttu-id="ddf03-244">İç içe geçmiş Try deyimleri</span><span class="sxs-lookup"><span data-stu-id="ddf03-244">Nested Try statements</span></span>

<span data-ttu-id="ddf03-245">Aşağıdaki örnek sahip bir `Try…Catch` bulunan deyimi bir `Try` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-245">The following example has a `Try…Catch` statement that is contained in a `Try` block.</span></span> <span data-ttu-id="ddf03-246">İç `Catch` blok olan bir özel durum oluşturursa, `InnerException` özgün özel durum özelliği.</span><span class="sxs-lookup"><span data-stu-id="ddf03-246">The inner `Catch` block throws an exception that has its `InnerException` property set to the original exception.</span></span> <span data-ttu-id="ddf03-247">Dış `Catch` blok raporları kendi özel ve iç özel durum.</span><span class="sxs-lookup"><span data-stu-id="ddf03-247">The outer `Catch` block reports its own exception and the inner exception.</span></span>

[!code-vb[VbVbalrStatements#93](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrStatements/VB/Class1.vb#93)]

### <a name="exception-handling-for-async-methods"></a><span data-ttu-id="ddf03-248">Özel durum işleme için zaman uyumsuz yöntemi</span><span class="sxs-lookup"><span data-stu-id="ddf03-248">Exception handling for async methods</span></span>

<span data-ttu-id="ddf03-249">Aşağıdaki örnekte, özel durum işleme için zaman uyumsuz yöntemler gösterilmektedir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-249">The following example illustrates exception handling for async methods.</span></span> <span data-ttu-id="ddf03-250">Zaman uyumsuz bir görev için geçerli bir özel durum yakalamak için `Await` ifade konusu bir `Try` bloğunu çağıran ve özel durum yakalandı `Catch` blok.</span><span class="sxs-lookup"><span data-stu-id="ddf03-250">To catch an exception that applies to an async task, the `Await` expression is in a `Try` block of the caller, and the exception is caught in the `Catch` block.</span></span>

<span data-ttu-id="ddf03-251">Açıklamadan çıkarın `Throw New Exception` özel durum işleme göstermek için örnek satır.</span><span class="sxs-lookup"><span data-stu-id="ddf03-251">Uncomment the `Throw New Exception` line in the example to demonstrate exception handling.</span></span> <span data-ttu-id="ddf03-252">Özel durum yakalandı `Catch` engelleme, görevin `IsFaulted` özelliği `True`ve görev `Exception.InnerException` özelliği, özel duruma ayarlanır.</span><span class="sxs-lookup"><span data-stu-id="ddf03-252">The exception is caught in the `Catch` block, the task's `IsFaulted` property is set to `True`, and the task's `Exception.InnerException` property is set to the exception.</span></span>

<span data-ttu-id="ddf03-253">Açıklamadan çıkarın `Throw New OperationCancelledException` zaman uyumsuz bir işlem iptal ettiğinizde ne göstermek için satır.</span><span class="sxs-lookup"><span data-stu-id="ddf03-253">Uncomment the `Throw New OperationCancelledException` line to demonstrate what happens when you cancel an asynchronous process.</span></span> <span data-ttu-id="ddf03-254">Özel durum yakalandı `Catch` blok ve görevin `IsCanceled` özelliği `True`.</span><span class="sxs-lookup"><span data-stu-id="ddf03-254">The exception is caught in the `Catch` block, and the task's `IsCanceled` property is set to `True`.</span></span> <span data-ttu-id="ddf03-255">Ancak, bu örnek için geçerli değildir bazı koşullar altında `IsFaulted` ayarlanır `True` ve `IsCanceled` ayarlanır `False`.</span><span class="sxs-lookup"><span data-stu-id="ddf03-255">However, under some conditions that don't apply to this example, `IsFaulted` is set to `True` and `IsCanceled` is set to `False`.</span></span>

[!code-vb[csAsyncExceptions#1](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/csasyncexceptions/vb/class1.vb#1)]

### <a name="handling-multiple-exceptions-in-async-methods"></a><span data-ttu-id="ddf03-256">Birden çok zaman uyumsuz yöntemlerde özel durumları işleme</span><span class="sxs-lookup"><span data-stu-id="ddf03-256">Handling multiple exceptions in async methods</span></span>

<span data-ttu-id="ddf03-257">Aşağıdaki örnek, özel durum işleme birden çok görev içinde birden çok özel durum burada sonuçlanabilir gösterir.</span><span class="sxs-lookup"><span data-stu-id="ddf03-257">The following example illustrates exception handling where multiple tasks can result in multiple exceptions.</span></span> <span data-ttu-id="ddf03-258">`Try` Bloğu `Await` görev ifadesi, <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=nameWithType> döndürdü.</span><span class="sxs-lookup"><span data-stu-id="ddf03-258">The `Try` block has the `Await` expression for the task that <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=nameWithType> returned.</span></span> <span data-ttu-id="ddf03-259">Üç, görevler, görev tamamlandığında <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=nameWithType> uygulanan getirildiğinden.</span><span class="sxs-lookup"><span data-stu-id="ddf03-259">The task is complete when the three tasks to which <xref:System.Threading.Tasks.Task.WhenAll%2A?displayProperty=nameWithType> is applied are complete.</span></span>

<span data-ttu-id="ddf03-260">Her biri üç görev, bir özel durum neden olur.</span><span class="sxs-lookup"><span data-stu-id="ddf03-260">Each of the three tasks causes an exception.</span></span> <span data-ttu-id="ddf03-261">`Catch` Blok yinelenir bulunan özel durumlar üzerinden `Exception.InnerExceptions` görevin özelliği, `Task.WhenAll` döndürdü.</span><span class="sxs-lookup"><span data-stu-id="ddf03-261">The `Catch` block iterates through the exceptions, which are found in the `Exception.InnerExceptions` property of the task that `Task.WhenAll` returned.</span></span>

[!code-vb[csAsyncExceptions#3](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/csasyncexceptions/vb/class1.vb#3)]

## <a name="see-also"></a><span data-ttu-id="ddf03-262">Ayrıca bkz.</span><span class="sxs-lookup"><span data-stu-id="ddf03-262">See also</span></span>

- <xref:Microsoft.VisualBasic.Information.Err%2A>
- <xref:System.Exception>
- [<span data-ttu-id="ddf03-263">Exit Deyimi</span><span class="sxs-lookup"><span data-stu-id="ddf03-263">Exit Statement</span></span>](exit-statement.md)
- [<span data-ttu-id="ddf03-264">On Error Deyimi</span><span class="sxs-lookup"><span data-stu-id="ddf03-264">On Error Statement</span></span>](on-error-statement.md)
- [<span data-ttu-id="ddf03-265">Kod Parçacıkları İçin En İyi Uygulamalar</span><span class="sxs-lookup"><span data-stu-id="ddf03-265">Best Practices for Using Code Snippets</span></span>](/visualstudio/ide/best-practices-for-using-code-snippets)
- [<span data-ttu-id="ddf03-266">Özel Durum İşleme</span><span class="sxs-lookup"><span data-stu-id="ddf03-266">Exception Handling</span></span>](../../../standard/parallel-programming/exception-handling-task-parallel-library.md)
- [<span data-ttu-id="ddf03-267">Throw Deyimi</span><span class="sxs-lookup"><span data-stu-id="ddf03-267">Throw Statement</span></span>](throw-statement.md)