---
title: "'Catch' bir 'Try' deyimi dışında yer alamaz"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: f9ce965d1d983743796f8cc66ae20ffb018a07bc
ms.sourcegitcommit: 0be8a279af6d8a43e03141e349d3efd5d35f8767
ms.translationtype: HT
ms.contentlocale: tr-TR
ms.lasthandoff: 04/18/2019
ms.locfileid: "59295919"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' bir 'Try' deyimi dışında yer alamaz
`Catch` içinde görünmelidir bir `Try...Catch...Finally` deyim bloğu. Ya da gereksiz bir sahip `Catch` deyiminde, `Try` bloğu veya `Catch` deyimi, karşılık gelen sınırları dışında görünür `Try` blok.  
  
 **Hata Kimliği:** BC30380  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1. Silme `Catch` gereksizdir veya içine yerleştirdiğiniz deyimi bir `Try...Catch...Finally` deyim bloğu.  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
