---
title: "'Catch' bir 'Try' ifadesi içinde 'Finally' sonra yer alamaz"
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: 13b8ce225fe487b0c597a6fe81983543e5af535e
ms.sourcegitcommit: 558d78d2a68acd4c95ef23231c8b4e4c7bac3902
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 04/09/2019
ms.locfileid: "59311337"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Catch' bir 'Try' ifadesi içinde 'Finally' sonra yer alamaz
A `Catch` koddan sonra deyimi görünür `Finally` biten bir `Try` deyim bloğu. `Catch` içinde görünmelidir bir `Try...Catch...Finally` deyim bloğu.  
  
 **Hata Kimliği:** BC30379  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1. Taşıma `Catch` kodda daha uygun bir yere deyimi.  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
