---
title: "'Catch' bir 'Try' ifadesi içinde 'Finally' sonra yer alamaz"
ms.date: 07/20/2015
f1_keywords:
- vbc30379
- bc30379
helpviewer_keywords:
- BC30379
ms.assetid: 33d1278b-cf10-4c66-aaf8-08a4372f370b
ms.openlocfilehash: f223eb0520cf625b5e66914188bcadf3ecf9cbd0
ms.sourcegitcommit: 5c1abeec15fbddcc7dbaa729fabc1f1f29f12045
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 03/15/2019
ms.locfileid: "58027081"
---
# <a name="catch-cannot-appear-after-finally-within-a-try-statement"></a>'Catch' bir 'Try' ifadesi içinde 'Finally' sonra yer alamaz
A `Catch` koddan sonra deyimi görünür `Finally` biten bir `Try` deyim bloğu. `Catch` içinde görünmelidir bir `Try...Catch...Finally` deyim bloğu.  
  
 **Hata Kimliği:** BC30379  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1.  Taşıma `Catch` kodda daha uygun bir yere deyimi.  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
