---
title: "'Throw' ifadesi işleneni, 'Catch' deyimi dışında veya 'Finally' deyimi içinde atlayamazsınız"
ms.date: 07/20/2015
f1_keywords:
- vbc30666
- bc30666
helpviewer_keywords:
- BC30666
ms.assetid: a208a6ea-0e36-4bf1-8984-4de1a0e38a2a
ms.openlocfilehash: 17e7817c608e9c3513e0320b62f42410613f33b0
ms.sourcegitcommit: 558d78d2a68acd4c95ef23231c8b4e4c7bac3902
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 04/09/2019
ms.locfileid: "59302497"
---
# <a name="throw-statement-cannot-omit-operand-outside-a-catch-statement-or-inside-a-finally-statement"></a>'Throw' ifadesi işleneni, 'Catch' deyimi dışında veya 'Finally' deyimi içinde atlayamazsınız
`Throw` deyimleri dışında `Catch` deyimi bir özel durum nesnesi adı sağlamanız gerekir.  
  
 **Hata Kimliği:** BC30666  
  
## <a name="to-correct-this-error"></a>Bu hatayı düzeltmek için  
  
1. Türetilen bir özel durum nesnesi adını `System.Exception`.  
  
2. Kodunuzu yeniden yapılandırmayı böylece `Throw` deyimdir içinde bir `Catch` blok.  
  
## <a name="see-also"></a>Ayrıca bkz.

- [Throw Deyimi](../../visual-basic/language-reference/statements/throw-statement.md)
- [Try...Catch...Finally Deyimi](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)
- <xref:System.Exception?displayProperty=nameWithType>
- [İşleme ve .NET özel durumları atma](../../standard/exceptions/index.md)
