---
title: 'Nasıl yapılır: Bir özel durum kullanarak try-catch - işleme C# Programlama Kılavuzu'
ms.custom: seodec18
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: 17b3be52bb89a1cf74bb8171ca937e434a8d94f1
ms.sourcegitcommit: 6b308cf6d627d78ee36dbbae8972a310ac7fd6c8
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 01/23/2019
ms.locfileid: "54552534"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="ac768-102">Nasıl yapılır: Bir özel durum try/catch kullanarak işleme (C# Programlama Kılavuzu)</span><span class="sxs-lookup"><span data-stu-id="ac768-102">How to: Handle an Exception Using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="ac768-103">Amacı, bir [try-catch](../../../csharp/language-reference/keywords/try-catch.md) bloğudur yakalayın ve çalışan kod tarafından oluşturulan bir özel durumu işle.</span><span class="sxs-lookup"><span data-stu-id="ac768-103">The purpose of a [try-catch](../../../csharp/language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="ac768-104">Bazı özel durumlar olarak işlenebilen bir `catch` bloğu ve sorun çözüldüğünde yeniden oluşturulmuş olan özel durum; ancak, daha sık yapmak için gereken tek şey uygun özel durum emin emin olun.</span><span class="sxs-lookup"><span data-stu-id="ac768-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="ac768-105">Örnek</span><span class="sxs-lookup"><span data-stu-id="ac768-105">Example</span></span>  
 <span data-ttu-id="ac768-106">Bu örnekte, <xref:System.IndexOutOfRangeException> en uygun özel durum değil: <xref:System.ArgumentOutOfRangeException> tarafından hata oluştuğundan, yöntem için daha anlamlı olur `index` bağımsız değişken geçirildi çağıran tarafından.</span><span class="sxs-lookup"><span data-stu-id="ac768-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](../../../csharp/programming-guide/exceptions/codesnippet/CSharp/how-to-handle-an-exception-using-try-catch_1.cs)]  
  
## <a name="comments"></a><span data-ttu-id="ac768-107">Açıklamalar</span><span class="sxs-lookup"><span data-stu-id="ac768-107">Comments</span></span>  
 <span data-ttu-id="ac768-108">Bir özel durum neden olan kod içine `try` blok.</span><span class="sxs-lookup"><span data-stu-id="ac768-108">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="ac768-109">A `catch` deyimi eklenir hemen sonra işlemeye `IndexOutOfRangeException`, meydana gelmesi durumunda.</span><span class="sxs-lookup"><span data-stu-id="ac768-109">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="ac768-110">`catch` Block tanıtıcıları `IndexOutOfRangeException` ve daha uygun `ArgumentOutOfRangeException` özel durumu yerine.</span><span class="sxs-lookup"><span data-stu-id="ac768-110">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="ac768-111">Çağıranın yazılımında mümkün olduğunca fazla bilgi için özgün özel durum olarak belirtmeyi düşünün <xref:System.Exception.InnerException%2A> yeni özel durum.</span><span class="sxs-lookup"><span data-stu-id="ac768-111">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="ac768-112">Çünkü <xref:System.Exception.InnerException%2A> özelliği [salt okunur](../../../csharp/language-reference/keywords/readonly.md), yeni özel durumun oluşturucuda atamanız gerekir.</span><span class="sxs-lookup"><span data-stu-id="ac768-112">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../../csharp/language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="ac768-113">Ayrıca bkz.</span><span class="sxs-lookup"><span data-stu-id="ac768-113">See also</span></span>

- [<span data-ttu-id="ac768-114">C# Programlama Kılavuzu</span><span class="sxs-lookup"><span data-stu-id="ac768-114">C# Programming Guide</span></span>](../../../csharp/programming-guide/index.md)
- [<span data-ttu-id="ac768-115">Özel Durumlar ve Özel Durum İşleme</span><span class="sxs-lookup"><span data-stu-id="ac768-115">Exceptions and Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/index.md)
- [<span data-ttu-id="ac768-116">Özel Durum İşleme</span><span class="sxs-lookup"><span data-stu-id="ac768-116">Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/exception-handling.md)
