---
title: 'Nasıl yapılır: Try-Catch- C# Programming kılavuzunu kullanarak özel durum işleme'
ms.custom: seodec18
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], try/catch blocks
- exceptions [C#], try/catch blocks
- try/catch blocks [C#]
ms.assetid: ca8e3773-980e-4767-8633-7408540e9818
ms.openlocfilehash: 5378de09962055fe7d2e100484ad69662c803e0f
ms.sourcegitcommit: 986f836f72ef10876878bd6217174e41464c145a
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 08/19/2019
ms.locfileid: "69590240"
---
# <a name="how-to-handle-an-exception-using-trycatch-c-programming-guide"></a><span data-ttu-id="df576-102">Nasıl yapılır: Try/catch kullanarak özel durum işleme (C# Programlama Kılavuzu)</span><span class="sxs-lookup"><span data-stu-id="df576-102">How to: Handle an Exception Using try/catch (C# Programming Guide)</span></span>
<span data-ttu-id="df576-103">[Try-catch](../../language-reference/keywords/try-catch.md) bloğunun amacı, çalışma kodu tarafından oluşturulan bir özel durumu yakalamak ve işleymelidir.</span><span class="sxs-lookup"><span data-stu-id="df576-103">The purpose of a [try-catch](../../language-reference/keywords/try-catch.md) block is to catch and handle an exception generated by working code.</span></span> <span data-ttu-id="df576-104">Bazı özel durumlar bir `catch` blokta işlenebilir ve sorun yeniden oluşturulan özel durum olmadan çözüldü; ancak, genellikle yapabileceğiniz tek şey uygun özel durumun atılmasından emin olabilir.</span><span class="sxs-lookup"><span data-stu-id="df576-104">Some exceptions can be handled in a `catch` block and the problem solved without the exception being re-thrown; however, more often the only thing that you can do is make sure that the appropriate exception is thrown.</span></span>  
  
## <a name="example"></a><span data-ttu-id="df576-105">Örnek</span><span class="sxs-lookup"><span data-stu-id="df576-105">Example</span></span>  
 <span data-ttu-id="df576-106">Bu örnekte, <xref:System.IndexOutOfRangeException> en uygun özel durum değildir: <xref:System.ArgumentOutOfRangeException> `index` hata, çağıran tarafından geçirilen bağımsız değişkenin nedeni olduğundan yöntem için daha anlamlı hale gelir.</span><span class="sxs-lookup"><span data-stu-id="df576-106">In this example, <xref:System.IndexOutOfRangeException> is not the most appropriate exception: <xref:System.ArgumentOutOfRangeException> makes more sense for the method because the error is caused by the `index` argument passed in by the caller.</span></span>  
  
 [!code-csharp[csProgGuideExceptions#5](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#5)]  
  
## <a name="comments"></a><span data-ttu-id="df576-107">Açıklamalar</span><span class="sxs-lookup"><span data-stu-id="df576-107">Comments</span></span>  
 <span data-ttu-id="df576-108">Özel duruma neden olan kod `try` bloğa alınmıştır.</span><span class="sxs-lookup"><span data-stu-id="df576-108">The code that causes an exception is enclosed in the `try` block.</span></span> <span data-ttu-id="df576-109">Bir `catch` ifade, gerçekleşirse, işleme `IndexOutOfRangeException`hemen sonra eklenir.</span><span class="sxs-lookup"><span data-stu-id="df576-109">A `catch` statement is added immediately after to handle `IndexOutOfRangeException`, if it occurs.</span></span> <span data-ttu-id="df576-110">Bloğu öğesini işler ve bunun yerine daha uygun `ArgumentOutOfRangeException` özel durumu oluşturur. `IndexOutOfRangeException` `catch`</span><span class="sxs-lookup"><span data-stu-id="df576-110">The `catch` block handles the `IndexOutOfRangeException` and throws the more appropriate `ArgumentOutOfRangeException` exception instead.</span></span> <span data-ttu-id="df576-111">Çağıranı mümkün olduğunca fazla bilgi sağlamak için, özgün özel durumu yeni özel durum olarak <xref:System.Exception.InnerException%2A> belirtmeyi göz önünde bulundurun.</span><span class="sxs-lookup"><span data-stu-id="df576-111">In order to provide the caller with as much information as possible, consider specifying the original exception as the <xref:System.Exception.InnerException%2A> of the new exception.</span></span> <span data-ttu-id="df576-112">Özelliği ReadOnly olduğundan, bunu yeni özel durumun oluşturucusunda atamanız gerekir. [](../../language-reference/keywords/readonly.md) <xref:System.Exception.InnerException%2A></span><span class="sxs-lookup"><span data-stu-id="df576-112">Because the <xref:System.Exception.InnerException%2A> property is [readonly](../../language-reference/keywords/readonly.md), you must assign it in the constructor of the new exception.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="df576-113">Ayrıca bkz.</span><span class="sxs-lookup"><span data-stu-id="df576-113">See also</span></span>

- [<span data-ttu-id="df576-114">C# Programlama Kılavuzu</span><span class="sxs-lookup"><span data-stu-id="df576-114">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="df576-115">Özel Durumlar ve Özel Durum İşleme</span><span class="sxs-lookup"><span data-stu-id="df576-115">Exceptions and Exception Handling</span></span>](./index.md)
- [<span data-ttu-id="df576-116">Özel Durum İşleme</span><span class="sxs-lookup"><span data-stu-id="df576-116">Exception Handling</span></span>](./exception-handling.md)
