---
title: Özel durumlar kullanma C# -Programlama Kılavuzu
ms.custom: seodec18
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], about exception handling
- exceptions [C#], about exceptions
ms.assetid: 71472c62-320a-470a-97d2-67995180389d
ms.openlocfilehash: 8d0fe4b8c2ba3e64aa7ee34fc9d02b29bda5c017
ms.sourcegitcommit: 986f836f72ef10876878bd6217174e41464c145a
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 08/19/2019
ms.locfileid: "69590175"
---
# <a name="using-exceptions-c-programming-guide"></a><span data-ttu-id="25063-102">Özel Durumlar Kullanma (C# Programlama Kılavuzu)</span><span class="sxs-lookup"><span data-stu-id="25063-102">Using Exceptions (C# Programming Guide)</span></span>
<span data-ttu-id="25063-103">İçinde C#, çalışma zamanında programdaki hatalar, özel durumlar adlı bir mekanizma kullanılarak program aracılığıyla dağıtılır.</span><span class="sxs-lookup"><span data-stu-id="25063-103">In C#, errors in the program at run time are propagated through the program by using a mechanism called exceptions.</span></span> <span data-ttu-id="25063-104">Özel durumlar, hata ile karşılaştığında ve hatayı düzeltebileceğiniz kodla yakalanan kodla oluşturulur.</span><span class="sxs-lookup"><span data-stu-id="25063-104">Exceptions are thrown by code that encounters an error and caught by code that can correct the error.</span></span> <span data-ttu-id="25063-105">Özel durumlar .NET Framework ortak dil çalışma zamanı (CLR) veya bir programdaki kodla oluşturulabilir.</span><span class="sxs-lookup"><span data-stu-id="25063-105">Exceptions can be thrown by the .NET Framework common language runtime (CLR) or by code in a program.</span></span> <span data-ttu-id="25063-106">Bir özel durum oluşturulduktan sonra, özel durum için bir `catch` ifade bulunana kadar çağrı yığınını yayar.</span><span class="sxs-lookup"><span data-stu-id="25063-106">Once an exception is thrown, it propagates up the call stack until a `catch` statement for the exception is found.</span></span> <span data-ttu-id="25063-107">Yakalanamayan özel durumlar, bir iletişim kutusu görüntüleyen sistem tarafından sunulan genel bir özel durum işleyicisi tarafından işlenir.</span><span class="sxs-lookup"><span data-stu-id="25063-107">Uncaught exceptions are handled by a generic exception handler provided by the system that displays a dialog box.</span></span>  
  
 <span data-ttu-id="25063-108">Özel durumlar, öğesinden <xref:System.Exception>türetilmiş sınıflar tarafından temsil edilir.</span><span class="sxs-lookup"><span data-stu-id="25063-108">Exceptions are represented by classes derived from <xref:System.Exception>.</span></span> <span data-ttu-id="25063-109">Bu sınıf, özel durum türünü tanımlar ve özel durumla ilgili ayrıntıları içeren özellikleri içerir.</span><span class="sxs-lookup"><span data-stu-id="25063-109">This class identifies the type of exception and contains properties that have details about the exception.</span></span> <span data-ttu-id="25063-110">Özel durum oluşturmak, özel durum türetilmiş sınıfın bir örneğini oluşturmayı, isteğe bağlı olarak özel durumun özelliklerini yapılandırmayı ve sonra `throw` anahtar sözcüğünü kullanarak nesneyi oluşturmayı içerir.</span><span class="sxs-lookup"><span data-stu-id="25063-110">Throwing an exception involves creating an instance of an exception-derived class, optionally configuring properties of the exception, and then throwing the object by using the `throw` keyword.</span></span> <span data-ttu-id="25063-111">Örneğin:</span><span class="sxs-lookup"><span data-stu-id="25063-111">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#1](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#1)]  
  
 <span data-ttu-id="25063-112">Bir özel durum oluşturulduktan sonra, çalışma zamanı bir `try` blok içinde olup olmadığını görmek için geçerli ifadeyi denetler.</span><span class="sxs-lookup"><span data-stu-id="25063-112">After an exception is thrown, the runtime checks the current statement to see whether it is within a `try` block.</span></span> <span data-ttu-id="25063-113">Eğer ise, `try` bloğuyla `catch` ilişkili herhangi bir blok, özel durumu yakalayıp yakalayamayacağını görmek için denetlenir.</span><span class="sxs-lookup"><span data-stu-id="25063-113">If it is, any `catch` blocks associated with the `try` block are checked to see whether they can catch the exception.</span></span> <span data-ttu-id="25063-114">`Catch`bloklar genellikle özel durum türlerini belirtir; `catch` bloğun türü özel durumla aynı türde veya özel durumun `catch` temel bir sınıfı ise, blok yöntemi işleyebilir.</span><span class="sxs-lookup"><span data-stu-id="25063-114">`Catch` blocks typically specify exception types; if the type of the `catch` block is the same type as the exception, or a base class of the exception, the `catch` block can handle the method.</span></span> <span data-ttu-id="25063-115">Örneğin:</span><span class="sxs-lookup"><span data-stu-id="25063-115">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#2](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#2)]  
  
 <span data-ttu-id="25063-116">Bir özel durum oluşturan ifade bir blok içinde `try` değilse veya `try` kendisini kapsayan blok eşleşen `catch` bir blok içindeyse, çalışma zamanı bir `try` deyimin ve `catch` blokların çağırma yöntemini denetler.</span><span class="sxs-lookup"><span data-stu-id="25063-116">If the statement that throws an exception is not within a `try` block or if the `try` block that encloses it has no matching `catch` block, the runtime checks the calling method for a `try` statement and `catch` blocks.</span></span> <span data-ttu-id="25063-117">Çalışma zamanı, arama yığınını devam ettirir ve uyumlu `catch` bir blok arar.</span><span class="sxs-lookup"><span data-stu-id="25063-117">The runtime continues up the calling stack, searching for a compatible `catch` block.</span></span> <span data-ttu-id="25063-118">Blok bulduktan ve yürütüldükten sonra, denetim bu `catch` blok sonrasında sonraki ifadeye geçirilir. `catch`</span><span class="sxs-lookup"><span data-stu-id="25063-118">After the `catch` block is found and executed, control is passed to the next statement after that `catch` block.</span></span>  
  
 <span data-ttu-id="25063-119">Bir `try` ifade, birden fazla `catch` blok içerebilir.</span><span class="sxs-lookup"><span data-stu-id="25063-119">A `try` statement can contain more than one `catch` block.</span></span> <span data-ttu-id="25063-120">Özel durumu `catch` işleyebilen ilk deyim yürütülür; uyumlu olsalar bile aşağıdaki `catch` deyimler yok sayılır.</span><span class="sxs-lookup"><span data-stu-id="25063-120">The first `catch` statement that can handle the exception is executed; any following `catch` statements, even if they are compatible, are ignored.</span></span> <span data-ttu-id="25063-121">Bu nedenle, catch blokları her zaman en belirli (veya en çok türetilen) en azından belirli bir şekilde sıralanmalıdır.</span><span class="sxs-lookup"><span data-stu-id="25063-121">Therefore, catch blocks should always be ordered from most specific (or most-derived) to least specific.</span></span> <span data-ttu-id="25063-122">Örneğin:</span><span class="sxs-lookup"><span data-stu-id="25063-122">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#3](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#3)]  
  
 <span data-ttu-id="25063-123">Blok yürütülmeden önce, çalışma zamanı `finally` blokları denetler. `catch`</span><span class="sxs-lookup"><span data-stu-id="25063-123">Before the `catch` block is executed, the runtime checks for `finally` blocks.</span></span> <span data-ttu-id="25063-124">`Finally`bloklar, programcı 'nin durdurulmuş `try` bir bloktan veya herhangi bir dış kaynağın (grafik tutamaçları, veritabanı bağlantıları veya dosya akışları gibi) çöp kutusu beklemeden serbest bırakılması için herhangi bir belirsiz durumu temizlemesini sağlar nesneleri sonlandırmak için çalışma zamanında toplayıcı.</span><span class="sxs-lookup"><span data-stu-id="25063-124">`Finally` blocks enable the programmer to clean up any ambiguous state that could be left over from an aborted `try` block, or to release any external resources (such as graphics handles, database connections or file streams) without waiting for the garbage collector in the runtime to finalize the objects.</span></span> <span data-ttu-id="25063-125">Örneğin:</span><span class="sxs-lookup"><span data-stu-id="25063-125">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#4](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#4)]  
  
 <span data-ttu-id="25063-126">Bir özel durum, çağrılırsa dosyayı yeniden açmaya çalışan ikinci `try` bloktaki kod başarısız `file.Close()` olur ve dosya kilitli kalır. `WriteByte()`</span><span class="sxs-lookup"><span data-stu-id="25063-126">If `WriteByte()` threw an exception, the code in the second `try` block that tries to reopen the file would fail if `file.Close()` is not called, and the file would remain locked.</span></span> <span data-ttu-id="25063-127">Bir özel durum oluşsa bile `finally` bloklaryürütüldüğüiçin,öncekiörnektekiblokdosyanındüzgünşekildekapatılmasınısağlarvebirhatadankaçınmayayardımcıolur.`finally`</span><span class="sxs-lookup"><span data-stu-id="25063-127">Because `finally` blocks are executed even if an exception is thrown, the `finally` block in the previous example allows for the file to be closed correctly and helps avoid an error.</span></span>  
  
 <span data-ttu-id="25063-128">Bir özel durum `catch` oluşturulduktan sonra çağrı yığınında uyumlu bir blok bulunmazsa, üç durumdan biri oluşur:</span><span class="sxs-lookup"><span data-stu-id="25063-128">If no compatible `catch` block is found on the call stack after an exception is thrown, one of three things occurs:</span></span>  
  
- <span data-ttu-id="25063-129">Özel durum bir Sonlandırıcı içindeyse Sonlandırıcı iptal edilir ve varsa taban sonlandırıcısı çağırılır.</span><span class="sxs-lookup"><span data-stu-id="25063-129">If the exception is within a finalizer, the finalizer is aborted and the base finalizer, if any, is called.</span></span>  
  
- <span data-ttu-id="25063-130">Çağrı yığını statik bir Oluşturucu içeriyorsa veya bir statik alan Başlatıcısı <xref:System.TypeInitializationException> varsa, özgün özel durum yeni özel durumun <xref:System.Exception.InnerException%2A> özelliğine atanır.</span><span class="sxs-lookup"><span data-stu-id="25063-130">If the call stack contains a static constructor, or a static field initializer, a <xref:System.TypeInitializationException> is thrown, with the original exception assigned to the <xref:System.Exception.InnerException%2A> property of the new exception.</span></span>  
  
- <span data-ttu-id="25063-131">İş parçacığının başlangıcına ulaşıldığında, iş parçacığı sonlandırılır.</span><span class="sxs-lookup"><span data-stu-id="25063-131">If the start of the thread is reached, the thread is terminated.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="25063-132">Ayrıca bkz.</span><span class="sxs-lookup"><span data-stu-id="25063-132">See also</span></span>

- [<span data-ttu-id="25063-133">C# Programlama Kılavuzu</span><span class="sxs-lookup"><span data-stu-id="25063-133">C# Programming Guide</span></span>](../index.md)
- [<span data-ttu-id="25063-134">Özel Durumlar ve Özel Durum İşleme</span><span class="sxs-lookup"><span data-stu-id="25063-134">Exceptions and Exception Handling</span></span>](./index.md)
