---
title: Özel durum - kullanarak C# Programlama Kılavuzu
ms.custom: seodec18
ms.date: 07/20/2015
helpviewer_keywords:
- exception handling [C#], about exception handling
- exceptions [C#], about exceptions
ms.assetid: 71472c62-320a-470a-97d2-67995180389d
ms.openlocfilehash: 9ab6c5029518cbe5deb0f2c5a16c99992022d7a3
ms.sourcegitcommit: 2701302a99cafbe0d86d53d540eb0fa7e9b46b36
ms.translationtype: MT
ms.contentlocale: tr-TR
ms.lasthandoff: 04/28/2019
ms.locfileid: "64595475"
---
# <a name="using-exceptions-c-programming-guide"></a><span data-ttu-id="60272-102">Özel Durumlar Kullanma (C# Programlama Kılavuzu)</span><span class="sxs-lookup"><span data-stu-id="60272-102">Using Exceptions (C# Programming Guide)</span></span>
<span data-ttu-id="60272-103">C# ' ta program çalışma zamanında hatalarını program aracılığıyla özel durumlar adlı bir mekanizmayı kullanarak yayılır.</span><span class="sxs-lookup"><span data-stu-id="60272-103">In C#, errors in the program at run time are propagated through the program by using a mechanism called exceptions.</span></span> <span data-ttu-id="60272-104">Özel durumlar hatayla karşılaştığında kod tarafından oluşturulur ve hatayı düzeltmek kodu tarafından yakalanan.</span><span class="sxs-lookup"><span data-stu-id="60272-104">Exceptions are thrown by code that encounters an error and caught by code that can correct the error.</span></span> <span data-ttu-id="60272-105">Özel durumlar, .NET Framework ortak dil çalışma zamanı (CLR) veya bir program kodunda atılabilir.</span><span class="sxs-lookup"><span data-stu-id="60272-105">Exceptions can be thrown by the .NET Framework common language runtime (CLR) or by code in a program.</span></span> <span data-ttu-id="60272-106">Bir özel durum sonra kadar çağrı yığınına yayan bir `catch` özel durum bildirimi bulundu.</span><span class="sxs-lookup"><span data-stu-id="60272-106">Once an exception is thrown, it propagates up the call stack until a `catch` statement for the exception is found.</span></span> <span data-ttu-id="60272-107">Yakalanmayan Özel durumların bir iletişim kutusu görüntüler sistem tarafından sağlanan bir genel özel durum işleyicisi tarafından işlenir.</span><span class="sxs-lookup"><span data-stu-id="60272-107">Uncaught exceptions are handled by a generic exception handler provided by the system that displays a dialog box.</span></span>  
  
 <span data-ttu-id="60272-108">Özel durumlar türetilmiş sınıflar tarafından temsil edilir <xref:System.Exception>.</span><span class="sxs-lookup"><span data-stu-id="60272-108">Exceptions are represented by classes derived from <xref:System.Exception>.</span></span> <span data-ttu-id="60272-109">Bu sınıf, özel durumun türünü tanımlar ve özel durumun ayrıntılarını sahip özellikler içerir.</span><span class="sxs-lookup"><span data-stu-id="60272-109">This class identifies the type of exception and contains properties that have details about the exception.</span></span> <span data-ttu-id="60272-110">Bir özel durum içeren bir özel durum türetilmiş sınıfın bir örneği oluşturma, isteğe bağlı olarak özel durumun özelliklerini yapılandırmak ve nesne kullanarak özel durum atma `throw` anahtar sözcüğü.</span><span class="sxs-lookup"><span data-stu-id="60272-110">Throwing an exception involves creating an instance of an exception-derived class, optionally configuring properties of the exception, and then throwing the object by using the `throw` keyword.</span></span> <span data-ttu-id="60272-111">Örneğin:</span><span class="sxs-lookup"><span data-stu-id="60272-111">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#1](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#1)]  
  
 <span data-ttu-id="60272-112">Bir özel durum oluştuktan sonra çalışma zamanı içinde olup olmadığını görmek için geçerli deyim denetler. bir `try` blok.</span><span class="sxs-lookup"><span data-stu-id="60272-112">After an exception is thrown, the runtime checks the current statement to see whether it is within a `try` block.</span></span> <span data-ttu-id="60272-113">Bunu varsa, `catch` ilişkili blokları `try` blok istisnayı yakalamak mümkündür olup olmadığını görmek için denetlenir.</span><span class="sxs-lookup"><span data-stu-id="60272-113">If it is, any `catch` blocks associated with the `try` block are checked to see whether they can catch the exception.</span></span> <span data-ttu-id="60272-114">`Catch` Bloklar, genellikle özel durum türlerini belirtin; varsa türünü `catch` bloğu özel durum ya da bir temel sınıf özel durumun, aynı türde `catch` blok yöntemi işleyebilir.</span><span class="sxs-lookup"><span data-stu-id="60272-114">`Catch` blocks typically specify exception types; if the type of the `catch` block is the same type as the exception, or a base class of the exception, the `catch` block can handle the method.</span></span> <span data-ttu-id="60272-115">Örneğin:</span><span class="sxs-lookup"><span data-stu-id="60272-115">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#2](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#2)]  
  
 <span data-ttu-id="60272-116">Bir özel durum deyimi içinde değilse, bir `try` blok veya `try` kendisini kapsayan bir blok eşleşen yok `catch` blok, çalışma zamanı denetimleri için yöntemi çağrılırken bir `try` deyimi ve `catch` engeller.</span><span class="sxs-lookup"><span data-stu-id="60272-116">If the statement that throws an exception is not within a `try` block or if the `try` block that encloses it has no matching `catch` block, the runtime checks the calling method for a `try` statement and `catch` blocks.</span></span> <span data-ttu-id="60272-117">Çalışma zamanı için bir uyumlu arama çağrı yığınına devam `catch` blok.</span><span class="sxs-lookup"><span data-stu-id="60272-117">The runtime continues up the calling stack, searching for a compatible `catch` block.</span></span> <span data-ttu-id="60272-118">Sonra `catch` bloğu bulundu ve yürütüldü, Denetim, bundan sonra sonraki deyime geçirilir `catch` blok.</span><span class="sxs-lookup"><span data-stu-id="60272-118">After the `catch` block is found and executed, control is passed to the next statement after that `catch` block.</span></span>  
  
 <span data-ttu-id="60272-119">A `try` deyimi birden fazla içerebilir `catch` blok.</span><span class="sxs-lookup"><span data-stu-id="60272-119">A `try` statement can contain more than one `catch` block.</span></span> <span data-ttu-id="60272-120">İlk `catch` özel durumu işleyebilecek deyimi yürütülür; tüm aşağıdaki `catch` deyimleri uyumlu olsalar bile yok sayılır.</span><span class="sxs-lookup"><span data-stu-id="60272-120">The first `catch` statement that can handle the exception is executed; any following `catch` statements, even if they are compatible, are ignored.</span></span> <span data-ttu-id="60272-121">Bu nedenle, catch blokları her zaman sıralı en belirli (veya en çok türetilen) az.</span><span class="sxs-lookup"><span data-stu-id="60272-121">Therefore, catch blocks should always be ordered from most specific (or most-derived) to least specific.</span></span> <span data-ttu-id="60272-122">Örneğin:</span><span class="sxs-lookup"><span data-stu-id="60272-122">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#3](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#3)]  
  
 <span data-ttu-id="60272-123">Önce `catch` bloğu yürütülür için çalışma zamanı denetimleri `finally` engeller.</span><span class="sxs-lookup"><span data-stu-id="60272-123">Before the `catch` block is executed, the runtime checks for `finally` blocks.</span></span> <span data-ttu-id="60272-124">`Finally` blokları etkinleştirme durdurulan kalabilir herhangi bir belirsiz durumu temizlemek Programcı `try` bloğu veya Çöp için beklemenize gerek kalmadan herhangi bir dış kaynağa (örneğin, grafik tanıtıcıları, veritabanı bağlantıları veya dosya akışları) serbest bırakmak için nesneleri sonlandırmak için toplayıcı çalışma zamanında.</span><span class="sxs-lookup"><span data-stu-id="60272-124">`Finally` blocks enable the programmer to clean up any ambiguous state that could be left over from an aborted `try` block, or to release any external resources (such as graphics handles, database connections or file streams) without waiting for the garbage collector in the runtime to finalize the objects.</span></span> <span data-ttu-id="60272-125">Örneğin:</span><span class="sxs-lookup"><span data-stu-id="60272-125">For example:</span></span>  
  
 [!code-csharp[csProgGuideExceptions#4](~/samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideExceptions/CS/Exceptions.cs#4)]  
  
 <span data-ttu-id="60272-126">Varsa `WriteByte()` ikinci kod özel durum oluşturdu `try` , dosyayı yeniden dener blok başarısız olurdu `file.Close()` çağrılmaz, dosyanın kilitli kalır.</span><span class="sxs-lookup"><span data-stu-id="60272-126">If `WriteByte()` threw an exception, the code in the second `try` block that tries to reopen the file would fail if `file.Close()` is not called, and the file would remain locked.</span></span> <span data-ttu-id="60272-127">Çünkü `finally` blokları, bir özel durum olsa bile, yürütülen `finally` blok önceki örnekte dosyanın doğru şekilde kapatılması sağlar ve kaçının bir hata yardımcı olur.</span><span class="sxs-lookup"><span data-stu-id="60272-127">Because `finally` blocks are executed even if an exception is thrown, the `finally` block in the previous example allows for the file to be closed correctly and helps avoid an error.</span></span>  
  
 <span data-ttu-id="60272-128">Hiçbir uyumlu değilse `catch` bloğu bulundu çağrı yığınındaki bir özel durum oluştuktan sonra üç şeylerden biri gerçekleşir:</span><span class="sxs-lookup"><span data-stu-id="60272-128">If no compatible `catch` block is found on the call stack after an exception is thrown, one of three things occurs:</span></span>  
  
- <span data-ttu-id="60272-129">Özel durum bir sonlandırıcı içinde ise, sonlandırıcı iptal edilir ve temel Sonlandırıcı varsa çağrılır.</span><span class="sxs-lookup"><span data-stu-id="60272-129">If the exception is within a finalizer, the finalizer is aborted and the base finalizer, if any, is called.</span></span>  
  
- <span data-ttu-id="60272-130">Çağrı yığınını statik oluşturucu veya bir statik alan başlatıcısında içeriyorsa bir <xref:System.TypeInitializationException> atanmış olan özgün özel durum ile oluşan <xref:System.Exception.InnerException%2A> yeni özel durum özelliği.</span><span class="sxs-lookup"><span data-stu-id="60272-130">If the call stack contains a static constructor, or a static field initializer, a <xref:System.TypeInitializationException> is thrown, with the original exception assigned to the <xref:System.Exception.InnerException%2A> property of the new exception.</span></span>  
  
- <span data-ttu-id="60272-131">İş parçacığının başlangıç ulaşılırsa, iş parçacığı sonlandırıldı.</span><span class="sxs-lookup"><span data-stu-id="60272-131">If the start of the thread is reached, the thread is terminated.</span></span>  
  
## <a name="see-also"></a><span data-ttu-id="60272-132">Ayrıca bkz.</span><span class="sxs-lookup"><span data-stu-id="60272-132">See also</span></span>

- [<span data-ttu-id="60272-133">C# Programlama Kılavuzu</span><span class="sxs-lookup"><span data-stu-id="60272-133">C# Programming Guide</span></span>](../../../csharp/programming-guide/index.md)
- [<span data-ttu-id="60272-134">Özel Durumlar ve Özel Durum İşleme</span><span class="sxs-lookup"><span data-stu-id="60272-134">Exceptions and Exception Handling</span></span>](../../../csharp/programming-guide/exceptions/index.md)
